# Use root/example as user/password credentials
version: '3.1'

services:
  fask_app:
    container_name: flask_container
    build:
      context: ./
      dockerfile: ./flask_app/Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    hostname: mongodb
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017